### ISSUE TITLE
use same cookie version as hyper

### ISSUE THREAD

**Issue by flosse** [iron/iron-sessionstorage#4]
I can't use `iron-sessionstorage` because it uses cookie `v0.4.x` and hyper uses `v0.3.x`. This leads to the following error:

`native library 'openssl' is being linked to by more than one version of the same package, but it can only be linked once; try pdating or pinning your dependencies to ensure that this package only shows up once`

**Comment by flosse** [comment]
I'm sorry, I missed that there is a `v0.3` of `iron-sessionstorage` ;-)

**Comment by untitaker** [comment]
Yeah 0.4 is broken, but we do need the new cookie version for #3... not sure how to fix.

**Comment by untitaker** [comment]
Pushed 0.5.0 which is the same as 0.3, mostly.

**Comment by zoumi** [comment]
Hyper had removed cookie from it dependencies.

**Comment by untitaker** [comment]
Yes, I already took care of that.
